# Project Configuration
group = org.calypsonet.keyple
title = Keyple Bluebird example
description = Keyple Bluebird example app with storage card management
version = 1.0.0

# Java Configuration
javaSourceLevel = 17
javaTargetLevel = 17

# UTF-8 required by javadoc for special characters (ex. copyright) with Java 11+
org.gradle.jvmargs = "-Dfile.encoding=UTF-8"

# Android Configuration (custom properties)
androidLibNamespace = org.calypsonet.keyple.plugin.bluebird
androidAppNamespace = org.calypsonet.keyple.example.plugin.bluebird
androidAppId = org.calypsonet.keyple.example.plugin.bluebird
androidAppVersionCode = 1
androidAppVersionName = 1.0
androidCompileSdk = 35
androidMinSdk = 28

# Android Project Configuration (global properties)
# Kotlin code style for this project ("official" or "obsolete"): use the official Kotlin coding conventions
kotlin.code.style=official
# Use AndroidX libraries instead of legacy Android Support libraries (required for modern Android)
android.useAndroidX=true
# Automatically convert third-party libraries using old support libraries to AndroidX (may slow builds)
android.enableJetifier=true
