///////////////////////////////////////////////////////////////////////////////
//  GRADLE CONFIGURATION
///////////////////////////////////////////////////////////////////////////////

plugins {
  id("com.android.application")
  id("kotlin-android")
  id("kotlin-parcelize")
  id("com.diffplug.spotless")
}

///////////////////////////////////////////////////////////////////////////////
//  APP CONFIGURATION
///////////////////////////////////////////////////////////////////////////////

dependencies {
  // private libraries (storage card)
  // Storage card specific components
  // Conditional dependency for the storage card library
  val storageCardLibName = "keyple-card-cna-storagecard-java-lib-2.2.0"
  val storageCardLibFile = file("libs/${storageCardLibName}.jar")
  if (storageCardLibFile.exists()) {
    println("Using private storage card library: ${storageCardLibFile.name}")
    implementation(files(storageCardLibFile))
  } else {
    println("Using mock storage card library")
    implementation(files("libs/${storageCardLibName}-mock.jar"))
  }

  // Conditional dependency for the storage card plugin library
  val pluginStorageCardLibName = "keyple-plugin-cna-storagecard-java-lib-1.1.0"
  val pluginStorageCardLibFile = file("libs/${pluginStorageCardLibName}.jar")
  if (pluginStorageCardLibFile.exists()) {
    println("Using private storage card plugin library: ${pluginStorageCardLibFile.name}")
    implementation(files(pluginStorageCardLibFile))
  } else {
    println("Using mock storage card plugin library")
    implementation(files("libs/${pluginStorageCardLibName}-mock.jar"))
  }

  // Bluebird specific components
  val bluebirdPluginLibName = "keyple-plugin-cna-bluebird-specific-nfc-java-lib-3.2.0"
  val bluebirdPluginLibFile = file("libs/${bluebirdPluginLibName}.aar")
  val bluebirdPluginDebugLibFile = file("libs/${bluebirdPluginLibName}-debug.aar")
  if (bluebirdPluginLibFile.exists()) {
    println("Using release Bluebird plugin library: ${bluebirdPluginLibFile.name}")
    implementation(files(bluebirdPluginLibFile))
  } else if (bluebirdPluginDebugLibFile.exists()) {
    println("Using debug Bluebird plugin library: ${bluebirdPluginDebugLibFile.name}")
    implementation(files(bluebirdPluginDebugLibFile))
  } else {
    println("Using mock Bluebird plugin library")
    implementation(files("libs/${bluebirdPluginLibName}-debug-mock.aar"))
  }

  // Begin Keyple configuration (generated by
  // 'https://keyple.org/components/overview/configuration-wizard/')
  implementation(platform("org.eclipse.keyple:keyple-java-bom:2026.02.20"))
  implementation("org.eclipse.keypop:keypop-reader-java-api")
  implementation("org.eclipse.keypop:keypop-calypso-card-java-api")
  implementation("org.eclipse.keypop:keypop-calypso-crypto-legacysam-java-api")
  implementation("org.eclipse.keypop:keypop-storagecard-java-api")
  implementation("org.eclipse.keyple:keyple-common-java-api")
  implementation("org.eclipse.keyple:keyple-util-java-lib")
  implementation("org.eclipse.keyple:keyple-service-java-lib")
  implementation("org.eclipse.keyple:keyple-card-calypso-java-lib")
  implementation("org.eclipse.keyple:keyple-plugin-storagecard-java-api")
  implementation("org.eclipse.keyple:keyple-card-calypso-crypto-legacysam-java-lib")

  // End Keyple configuration

  // Android components
  implementation("androidx.appcompat:appcompat:1.7.1")
  implementation("com.google.android.material:material:1.13.0")
  implementation("androidx.constraintlayout:constraintlayout:2.2.1")
  implementation("androidx.activity:activity-ktx:1.10.1")
  implementation("androidx.fragment:fragment-ktx:1.8.9")
  // Coroutines
  implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.10.2")
  implementation("org.jetbrains.kotlinx:kotlinx-coroutines-android:1.10.2")
  // Logging libraries used in the project:
  // - SLF4J API provides a common logging interface for the app and third-party libraries (e.g.,
  //   Keyple).
  // - slf4j-timber bridges SLF4J calls to Timber for Android logging.
  // - Timber is used as the primary Android logging framework, offering lightweight and flexible
  //   logging.
  implementation("org.slf4j:slf4j-api:1.7.36")
  implementation("com.arcao:slf4j-timber:3.1@aar")
  implementation("com.jakewharton.timber:timber:5.0.1")
}

///////////////////////////////////////////////////////////////////////////////
//  STANDARD CONFIGURATION FOR ANDROID APPLICATION KOTLIN-BASED PROJECTS
///////////////////////////////////////////////////////////////////////////////

val javaSourceLevel: String by project
val javaTargetLevel: String by project

android {
  namespace = project.findProperty("androidAppNamespace") as String
  compileSdk = (project.findProperty("androidCompileSdk") as String).toInt()
  defaultConfig {
    applicationId = project.findProperty("androidAppId") as String
    minSdk = (project.findProperty("androidMinSdk") as String).toInt()
    targetSdk = (project.findProperty("androidCompileSdk") as String).toInt()
    versionCode = (project.findProperty("androidAppVersionCode") as String).toInt()
    versionName = project.findProperty("androidAppVersionName") as String
  }
  buildFeatures {
    buildConfig = true
    viewBinding = true
  }
  buildTypes {
    // Configuration for the debug build variant:
    // - Minification, resource shrinking, and ProGuard rules are enabled here as an example
    //   to test release-like performance and optimizations during development.
    // - To see full, unoptimized logs during debug, this block can be commented out or adjusted.
    getByName("debug") {
      isMinifyEnabled = true
      isShrinkResources = true
      proguardFiles(getDefaultProguardFile("proguard-android-optimize.txt"), "proguard-rules.pro")
    }
    getByName("release") {
      isMinifyEnabled = true
      isShrinkResources = true
      proguardFiles(getDefaultProguardFile("proguard-android-optimize.txt"), "proguard-rules.pro")
    }
  }
  compileOptions {
    sourceCompatibility = JavaVersion.toVersion(javaSourceLevel)
    targetCompatibility = JavaVersion.toVersion(javaTargetLevel)
  }
  kotlin { jvmToolchain(javaTargetLevel.substringAfterLast('.').toInt()) }
  sourceSets {
    getByName("main").java.srcDirs("src/main/kotlin")
    getByName("debug").java.srcDirs("src/debug/kotlin")
  }
  packagingOptions {
    // Exclude 'META-INF/NOTICE.md' to resolve the conflict that occurs when multiple dependencies
    // include this file
    resources.excludes.add("META-INF/NOTICE.md")
  }
  applicationVariants.all {
    outputs.all {
      val outputImpl = this as com.android.build.gradle.internal.api.ApkVariantOutputImpl
      val variantName = name
      val versionName = defaultConfig.versionName
      val newName = "${rootProject.name}-$versionName-$variantName.apk"
      outputImpl.outputFileName = newName
    }
  }
  lint { abortOnError = false }
}
