plugins {
    id("com.android.application")
    id("kotlin-android")
    id("kotlin-parcelize")
    id("com.diffplug.spotless")
}

android {
    namespace = "org.calypsonet.keyple.plugin.androidnfc.example"
    compileSdk = 35

    buildFeatures {
        viewBinding = true
    }

    defaultConfig {
        applicationId = "org.calypsonet.keyple.plugin.androidnfc.example"
        minSdk = 24
        targetSdk = 35
        versionName = project.version.toString()
    }

    buildTypes {
        getByName("release") {
            isMinifyEnabled = false
            proguardFiles(
                getDefaultProguardFile("proguard-android-optimize.txt"),
                "proguard-rules.pro"
            )
        }
    }

    val javaSourceLevel: String by project
    val javaTargetLevel: String by project
    compileOptions {
        sourceCompatibility = JavaVersion.toVersion(javaSourceLevel)
        targetCompatibility = JavaVersion.toVersion(javaTargetLevel)
    }

    kotlinOptions {
        jvmTarget = javaTargetLevel
    }

    packaging {
        resources {
            excludes.add("META-INF/NOTICE.md")
            excludes.add("META-INF/LICENSE.md")
            excludes.add("META-INF/LICENSE-notice.md")
        }
    }

    lint {
        abortOnError = false
    }

    sourceSets {
        getByName("main").java.srcDirs("src/main/kotlin")
        getByName("test").java.srcDirs("src/test/kotlin")
    }
}

dependencies {
    // private libraries (storage card)
    implementation(fileTree(mapOf("dir" to "libs", "include" to listOf("*.jar", "*.aar"))))

    // Kotlin
    implementation(kotlin("stdlib-jdk8"))
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.9.0")

    // Begin Keyple configuration (generated by 'https://keyple.org/components/overview/configuration-wizard/')
    implementation(platform("org.eclipse.keyple:keyple-java-bom:2025.12.12"))
    implementation("org.eclipse.keypop:keypop-reader-java-api")
    implementation("org.eclipse.keypop:keypop-calypso-card-java-api")
    implementation("org.eclipse.keypop:keypop-storagecard-java-api:1.1.0-SNAPSHOT") { isChanging = true }
    implementation("org.eclipse.keyple:keyple-common-java-api")
    implementation("org.eclipse.keyple:keyple-util-java-lib")
    implementation("org.eclipse.keyple:keyple-service-java-lib")
    implementation("org.eclipse.keyple:keyple-card-calypso-java-lib")
    // End Keyple configuration

    // Android components
    implementation("androidx.appcompat:appcompat:1.7.0")
    implementation("androidx.cardview:cardview:1.0.0")
    implementation("androidx.recyclerview:recyclerview:1.4.0")
    implementation("androidx.constraintlayout:constraintlayout:2.2.0")

    // Logging
    implementation("com.jakewharton.timber:timber:5.0.1")
    implementation("com.arcao:slf4j-timber:3.1@aar")
}