// /////////////////////////////////////////////////////////////////////////////
//  GRADLE CONFIGURATION
// /////////////////////////////////////////////////////////////////////////////
plugins {
    java
    id("com.diffplug.spotless") version "6.25.0"
}
buildscript {
    repositories {
        mavenLocal()
        mavenCentral()
    }
}

// /////////////////////////////////////////////////////////////////////////////
//  APP CONFIGURATION
// /////////////////////////////////////////////////////////////////////////////
repositories {
    mavenLocal()
    mavenCentral()
    maven(url = "https://central.sonatype.com/repository/maven-snapshots/")
}
dependencies {
    // private libraries
    // Storage card specific components
    // Conditional dependency for the storage card library
    val storageCardLibName = "keyple-card-cna-storagecard-java-lib-2.2.0"
    val storageCardLibFile = file("libs/$storageCardLibName.jar")
    if (storageCardLibFile.exists()) {
        println("Using private storage card library: ${storageCardLibFile.name}")
        implementation(files(storageCardLibFile))
    } else {
        println("Using mock storage card library")
        implementation(files("libs/$storageCardLibName-mock.jar"))
    }
// Begin Keyple configuration (generated by 'https://keyple.org/components/overview/configuration-wizard/')
    implementation(platform("org.eclipse.keyple:keyple-java-bom:2025.12.12"))
    implementation("org.eclipse.keypop:keypop-reader-java-api")
    implementation("org.eclipse.keypop:keypop-calypso-card-java-api")
    implementation("org.eclipse.keypop:keypop-storagecard-java-api:1.1.0")
    implementation("org.eclipse.keyple:keyple-common-java-api")
    implementation("org.eclipse.keyple:keyple-util-java-lib")
    implementation("org.eclipse.keyple:keyple-service-java-lib")
    implementation("org.eclipse.keyple:keyple-card-calypso-java-lib")
    implementation("org.eclipse.keyple:keyple-plugin-pcsc-java-lib:2.6.1")
// End Keyple configuration

    implementation("org.slf4j:slf4j-simple:1.7.36")
}

val javaSourceLevel: String by project
val javaTargetLevel: String by project
java {
    sourceCompatibility = JavaVersion.toVersion(javaSourceLevel)
    targetCompatibility = JavaVersion.toVersion(javaTargetLevel)
    println("Compiling Java $sourceCompatibility to Java $targetCompatibility.")
}

// /////////////////////////////////////////////////////////////////////////////
//  TASKS CONFIGURATION
// /////////////////////////////////////////////////////////////////////////////
tasks {
    spotless {
        java {
            target("src/**/*.java")
            licenseHeaderFile("${project.rootDir}/LICENSE_HEADER")
            importOrder("java", "javax", "org", "com", "")
            removeUnusedImports()
            googleJavaFormat()
        }
        kotlinGradle {
            target("*.gradle.kts")
            ktlint()
        }
    }
}
